name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to GCP
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev

    - name: Build and tag Docker image
      run: |
        IMAGE_TAG=europe-west9-docker.pkg.dev/infal-devops-sysops/student-tony/monapp:${{ github.sha }}
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push Docker image to GCP Container Registry
      run: |
        IMAGE_TAG=europe-west9-docker.pkg.dev/infal-devops-sysops/student-tony/monapp:${{ github.sha }}
        docker push $IMAGE_TAG
